<a href="https://colab.research.google.com/github/omdgit/RL_pytorch/blob/master/2019_09_22_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch tutorial  
## PyTorch tutorial  
link: [colab tutorial](https://colab.research.google.com/drive/1gJAAN3UI9005ecVmxPun5ZLCGu4YBtLo#scrollTo=p2mwWav-iMPh)

In [1]:
import sys
print(sys.version)

3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]


In [0]:
# make sure to enable GPU acceleration!
device = 'cuda'

!pip3 install torch torchvision

In [0]:
!pip3 install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl

     |████████████████████████████████| 592.3MB 1.3MB/s 
ERROR: torchvision 0.3.0 has requirement torch>=1.1.0, but you'll have torch 0.3.0.post4 which is incompatible.
ERROR: fastai 1.0.57 has requirement torch>=1.0.0, but you'll have torch 0.3.0.post4 which is incompatible.
  Found existing installation: torch 1.1.0
    Uninstalling torch-1.1.0:
      Successfully uninstalled torch-1.1.0


In [0]:
!pip3 install torchvision

     |████████████████████████████████| 748.9MB 27kB/s 
  Found existing installation: torch 0.3.0.post4
    Uninstalling torch-0.3.0.post4:
      Successfully uninstalled torch-0.3.0.post4


In [0]:
import torch

In [0]:
x = torch.rand(5, 3)

In [5]:
print(x)

tensor([[0.0240, 0.8628, 0.3548],
        [0.5947, 0.7264, 0.7625],
        [0.4274, 0.0245, 0.8697],
        [0.3920, 0.8039, 0.6226],
        [0.9197, 0.6609, 0.4910]])


In [6]:
torch.cuda.is_available()

True

### Create some tensors

In [7]:
# sample tensor (1 dimension)
a = torch.rand(5)

# sample tensor (2 dimension)
b = torch.zeros(3, 3)

# sample tensor (... dimension)
c = torch.ones(3,1,3,2,4)

print(a)
print(b)
print(c)

tensor([0.7598, 0.4042, 0.4525, 0.1922, 0.6505])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[[[[1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.]]]]])


### Enable GPU Usage with PyTorch

In [0]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
  print('GPU is not available')

In [9]:
# create PyTorch tensor
x = torch.rand(5,5)

# attach tensor to GPU device
x = x.to(device)
print('Is tensor x on the GPU {} '.format(x.is_cuda))
print(x)

Is tensor x on the GPU True 
tensor([[0.4540, 0.3330, 0.3672, 0.1419, 0.2914],
        [0.8033, 0.4212, 0.8801, 0.9947, 0.3709],
        [0.1669, 0.3675, 0.6973, 0.6134, 0.9394],
        [0.5866, 0.9739, 0.9903, 0.3577, 0.9604],
        [0.0451, 0.2604, 0.9179, 0.7208, 0.2304]], device='cuda:0')


In [10]:
import keras

Using TensorFlow backend.
