<a href="https://colab.research.google.com/github/omdgit/RL_pytorch/blob/master/2019_09_22_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch tutorial  
## PyTorch tutorial  
link: [colab tutorial](https://colab.research.google.com/drive/1gJAAN3UI9005ecVmxPun5ZLCGu4YBtLo#scrollTo=p2mwWav-iMPh)

In [7]:
import sys
print(sys.version)

3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]


In [0]:
# make sure to enable GPU acceleration!
device = 'cuda'

!pip3 install torch torchvision

In [11]:
!pip3 install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl

     |████████████████████████████████| 592.3MB 1.3MB/s 
ERROR: torchvision 0.3.0 has requirement torch>=1.1.0, but you'll have torch 0.3.0.post4 which is incompatible.
ERROR: fastai 1.0.57 has requirement torch>=1.0.0, but you'll have torch 0.3.0.post4 which is incompatible.
  Found existing installation: torch 1.1.0
    Uninstalling torch-1.1.0:
      Successfully uninstalled torch-1.1.0


In [12]:
!pip3 install torchvision

     |████████████████████████████████| 748.9MB 27kB/s 
  Found existing installation: torch 0.3.0.post4
    Uninstalling torch-0.3.0.post4:
      Successfully uninstalled torch-0.3.0.post4


In [0]:
import torch

In [0]:
x = torch.rand(5, 3)

In [15]:
print(x)

tensor([[0.7713, 0.8527, 0.7914],
        [0.0549, 0.6341, 0.8507],
        [0.9829, 0.1405, 0.1914],
        [0.0825, 0.1346, 0.6233],
        [0.6490, 0.7270, 0.5819]])


In [16]:
torch.cuda.is_available()

True

### Create some tensors

In [19]:
# sample tensor (1 dimension)
a = torch.rand(5)

# sample tensor (2 dimension)
b = torch.zeros(3, 3)

c = torch.ones(3,1,3,2,4)

print(a)
print(b)
print(c)

tensor([0.8851, 0.7390, 0.0595, 0.7693, 0.2244])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[[[[1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.]]]]])


### Enable GPU Usage with PyTorch

In [0]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
  print('GPU is not available')

In [23]:
# create PyTorch tensor
x = torch.rand(5,5)

# attach tensor to GPU device
x = x.to(device)
print('Is tensor x on the GPU {} '.format(x.is_cuda))
print(x)

Is tensor x on the GPU True 
tensor([[0.5261, 0.4344, 0.0157, 0.7696, 0.8140],
        [0.1955, 0.5572, 0.3426, 0.0067, 0.4236],
        [0.4286, 0.9775, 0.9571, 0.1305, 0.1386],
        [0.9562, 0.6139, 0.9937, 0.5987, 0.2161],
        [0.2951, 0.3642, 0.1456, 0.3005, 0.6616]], device='cuda:0')
